## config.yaml
openai:
  api_key: "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"
  model: "gpt-3.5-turbo"
  #api_key: "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"
  #model: "gpt-4"
refresh_time: 60
models:
  - "gpt-3.5-turbo"
  - "code-davinci-002"
  - "text-davinci-003"
  - "gpt-4"
allowed_types: ['image/jpeg', 'image/png']
max_size: 5 * 1024 * 1024
